<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/css/_all-skins.min.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="/css/bootstrap-datepicker.min.css">
    <!-- Time Picker -->
    <link rel="stylesheet" href="/css/bootstrap-timepicker.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="/" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>S</b>B</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Siang</b>Bang</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/img/avatar5.png" class="user-image" alt="User Image">
                                <span class="hidden-xs">
                                    <?php echo $_SESSION['name'] ?>
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="/img/avatar5.png" class="img-circle" alt="User Image">
                                    <p>
                                        <?php echo $_SESSION['name']." - ".ucwords(str_replace("_", " ", $_SESSION['role'])); ?>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="/logout" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="/img/avatar5.png" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>
                            <?php echo $_SESSION['name'] ?>
                        </p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>
                    <li <?php if (empty($function)) echo "class='active'";?>>
                        <a href="/dashboard">
                            <i class="fa fa-dashboard"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <?php if ($_SESSION['role'] == 'admin_barang' || $_SESSION['role'] == 'mahasiswa') : ?>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-laptop"></i>
                            <span>Barang</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="daftar-barang"><i class="fa fa-circle-o"></i> Barang Tersedia</a>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <?php if ($_SESSION['role'] == 'mahasiswa') : ?>
                    <li class="treeview <?php if ($function == 'pinjam-barang' || $function == 'pinjam-ruang') echo "active";?>">
                        <a href="#">
                            <i class="fa fa-plus-square"></i>
                            <span>Peminjaman</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li <?php if ($function == 'pinjam-barang') echo "class='active'";?>>
                                <a href="pinjam-barang"><i class="fa fa-circle-o"></i> Peminjaman Barang</a>
                            </li>
                            <li <?php if ($function == 'pinjam-ruang') echo "class='active'";?>>
                                <a href="pinjam-ruang"><i class="fa fa-circle-o"></i> Peminjaman Ruang</a>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <li>
                        <a href="pages/widgets.html">
                            <i class="fa fa-th"></i>
                            <span>Widgets</span>
                            <span class="pull-right-container">
                                <small class="label pull-right bg-green">new</small>
                            </span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-pie-chart"></i>
                            <span>Charts</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a>
                            </li>
                            <li>
                                <a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a>
                            </li>
                            <li>
                                <a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a>
                            </li>
                            <li>
                                <a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a>
                            </li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-laptop"></i>
                            <span>UI Elements</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a>
                            </li>
                            <li>
                                <a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a>
                            </li>
                            <li>
                                <a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a>
                            </li>
                            <li>
                                <a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a>
                            </li>
                            <li>
                                <a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a>
                            </li>
                            <li>
                                <a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a>
                            </li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-edit"></i>
                            <span>Forms</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a>
                            </li>
                            <li>
                                <a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a>
                            </li>
                            <li>
                                <a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a>
                            </li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-table"></i>
                            <span>Tables</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a>
                            </li>
                            <li>
                                <a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="pages/calendar.html">
                            <i class="fa fa-calendar"></i>
                            <span>Calendar</span>
                            <span class="pull-right-container">
                                <small class="label pull-right bg-red">3</small>
                                <small class="label pull-right bg-blue">17</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="pages/mailbox/mailbox.html">
                            <i class="fa fa-envelope"></i>
                            <span>Mailbox</span>
                            <span class="pull-right-container">
                                <small class="label pull-right bg-yellow">12</small>
                                <small class="label pull-right bg-green">16</small>
                                <small class="label pull-right bg-red">5</small>
                            </span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-folder"></i>
                            <span>Examples</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a>
                            </li>
                            <li>
                                <a href="pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a>
                            </li>
                            <li>
                                <a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a>
                            </li>
                            <li>
                                <a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a>
                            </li>
                            <li>
                                <a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a>
                            </li>
                            <li>
                                <a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a>
                            </li>
                            <li>
                                <a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a>
                            </li>
                            <li>
                                <a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a>
                            </li>
                            <li>
                                <a href="pages/examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a>
                            </li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-share"></i>
                            <span>Multilevel</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="#"><i class="fa fa-circle-o"></i> Level One</a>
                            </li>
                            <li class="treeview">
                                <a href="#"><i class="fa fa-circle-o"></i> Level One
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li>
                                        <a href="#"><i class="fa fa-circle-o"></i> Level Two</a>
                                    </li>
                                    <li class="treeview">
                                        <a href="#"><i class="fa fa-circle-o"></i> Level Two
                                            <span class="pull-right-container">
                                                <i class="fa fa-angle-left pull-right"></i>
                                            </span>
                                        </a>
                                        <ul class="treeview-menu">
                                            <li>
                                                <a href="#"><i class="fa fa-circle-o"></i> Level Three</a>
                                            </li>
                                            <li>
                                                <a href="#"><i class="fa fa-circle-o"></i> Level Three</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-circle-o"></i> Level One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="https://adminlte.io/docs"><i class="fa fa-book"></i>
                            <span>Documentation</span>
                        </a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <?php if (isset($function)) {
                    
                switch ($function) {
                    case 'daftar-barang':
                        require_once(__DIR__.'/layouts/daftar-barang.php');
                        break;

                    case 'pinjam-barang':
                        require_once(__DIR__.'/layouts/pinjam-barang.php');
                        break;

                    case 'pinjam-ruang':
                        require_once(__DIR__.'/layouts/pinjam-ruang.php');
                        break;
                  
                    default:
                        require_once(__DIR__.'/layouts/default.php');
                        break;
                }
              
            } else {
                require_once(__DIR__.'/layouts/default.php');
            } ?>
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0
            </div>
            <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="/js/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/js/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
    $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- datepicker -->
    <script src="/js/bootstrap-datepicker.min.js"></script>
    <!-- timepicker -->
    <script src="/js/bootstrap-timepicker.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/js/adminlte.min.js"></script>
    <script type="text/javascript">
      $('.datepicker').datepicker({
        orientation: 'bottom',
        format: 'yyyy-mm-dd'
      });

      //Timepicker
      $('.timepicker').timepicker({
        showInputs: false
      })
    </script>
</body>

</html>