<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/css/_all-skins.min.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="/css/bootstrap-datepicker.min.css">
    <!-- Time Picker -->
    <link rel="stylesheet" href="/css/bootstrap-timepicker.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="/" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>S</b>B</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Siang</b>Bang</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/img/avatar5.png" class="user-image" alt="User Image">
                                <span class="hidden-xs">
                                    <?php echo $_SESSION['name'] ?>
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="/img/avatar5.png" class="img-circle" alt="User Image">
                                    <p>
                                        <?php echo $_SESSION['name']." - ".ucwords(str_replace("_", " ", $_SESSION['role'])); ?>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="/logout" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="/img/avatar5.png" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>
                            <?php echo $_SESSION['name'] ?>
                        </p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>
                    <li <?php if (empty($function)) echo "class='active'";?>>
                        <a href="/dashboard">
                            <i class="fa fa-dashboard"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <?php if ($_SESSION['role'] == 'admin_ruangan' || $_SESSION['role'] == 'mahasiswa') : ?>
                    <li class="treeview <?php if ($function == 'daftar-ruang' || $function == 'list-pinjam-ruang' || $function == 'entry-jadwal') echo "active";?>">
                        <a href="#">
                            <i class="fa fa-building"></i>
                            <span>Ruangan</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li <?php if ($function == 'daftar-ruang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>daftar-ruang"><i class="fa fa-circle-o"></i> Ruangan Tersedia</a>
                            </li>
                            <?php if ($_SESSION['role'] == 'admin_ruangan') : ?>
                            <li <?php if ($function == 'list-pinjam-ruang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>list-pinjam-ruang"><i class="fa fa-circle-o"></i> Daftar Peminjaman Ruangan</a>
                            </li>
                            <li <?php if ($function == 'entry-jadwal') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>entry-jadwal"><i class="fa fa-circle-o"></i> Entry Jadwal Ruangan</a>
                            </li>
                            <?php endif; ?>
                            <li>
                                <a href="/jadwal-ruangan"><i class="fa fa-circle-o"></i> Lihat Jadwal</a>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <?php if ($_SESSION['role'] == 'admin_barang' || $_SESSION['role'] == 'mahasiswa') : ?>
                    <li class="treeview <?php if ($function == 'daftar-barang') echo "active";?>">
                        <a href="#">
                            <i class="fa fa-laptop"></i>
                            <span>Barang</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li <?php if ($function == 'daftar-barang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>daftar-barang"><i class="fa fa-circle-o"></i> Barang Tersedia</a>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <?php if ($_SESSION['role'] == 'mahasiswa') : ?>
                    <li class="treeview <?php if ($function == 'pinjam-barang' || $function == 'pinjam-ruang') echo "active";?>">
                        <a href="#">
                            <i class="fa fa-plus-square"></i>
                            <span>Peminjaman</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li <?php if ($function == 'pinjam-barang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>pinjam-barang"><i class="fa fa-circle-o"></i> Pinjam Barang</a>
                            </li>
                            <li <?php if ($function == 'pinjam-ruang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>pinjam-ruang"><i class="fa fa-circle-o"></i> Pinjam Ruangan</a>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <?php if ($_SESSION['role'] == 'mahasiswa') : ?>
                    <li class="treeview <?php if ($function == 'riwayat-barang' || $function == 'riwayat-ruang') echo "active";?>">
                        <a href="#">
                            <i class="fa fa-history"></i>
                            <span>Riwayat</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li <?php if ($function == 'riwayat-barang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>riwayat-barang"><i class="fa fa-circle-o"></i> Riwayat Peminjaman Barang</a>
                            </li>
                            <li <?php if ($function == 'riwayat-ruang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>riwayat-ruang"><i class="fa fa-circle-o"></i> Riwayat Peminjaman Ruangan</a>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <?php if ($_SESSION['role'] == 'mahasiswa') : ?>
                    <li class="treeview <?php if ($function == 'cetak-barang' || $function == 'cetak-ruang') echo "active";?>">
                        <a href="#">
                            <i class="fa fa-print"></i>
                            <span>Cetak Bukti</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li <?php if ($function == 'cetak-barang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>cetak-barang"><i class="fa fa-circle-o"></i> Bukti Peminjaman Barang</a>
                            </li>
                            <li <?php if ($function == 'cetak-ruang') echo "class='active'";?>>
                                <a href="<?php if (empty($function)) echo "dashboard/" ?>cetak-ruang"><i class="fa fa-circle-o"></i> Bukti Peminjaman Ruangan</a>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <?php if (isset($function)) {
                    
                switch ($function) {
                    case 'daftar-barang':
                        require_once(__DIR__.'/layouts/daftar-barang.php');
                        break;

                    case 'daftar-ruang':
                        require_once(__DIR__.'/layouts/daftar-ruang.php');
                        break;

                    case 'daftar-barang':
                        require_once(__DIR__.'/layouts/daftar-barang.php');
                        break;

                    case 'pinjam-barang':
                        require_once(__DIR__.'/layouts/pinjam-barang.php');
                        break;

                    case 'pinjam-ruang':
                        require_once(__DIR__.'/layouts/pinjam-ruang.php');
                        break;

                    case 'list-pinjam-barang':
                        require_once(__DIR__.'/layouts/list-pinjam-barang.php');
                        break;

                    case 'list-pinjam-ruang':
                        require_once(__DIR__.'/layouts/list-pinjam-ruang.php');
                        break;

                    case 'riwayat-barang':
                        require_once(__DIR__.'/layouts/riwayat-barang.php');
                        break;

                    case 'riwayat-ruang':
                        require_once(__DIR__.'/layouts/riwayat-ruang.php');
                        break;

                    case 'cetak-barang':
                        require_once(__DIR__.'/layouts/cetak-barang.php');
                        break;

                    case 'cetak-ruang':
                        require_once(__DIR__.'/layouts/cetak-ruang.php');
                        break;

                    case 'entry-jadwal':
                        require_once(__DIR__.'/layouts/entry-jadwal.php');
                        break;
                  
                    default:
                        require_once(__DIR__.'/layouts/default.php');
                        break;
                }
              
            } else {
                require_once(__DIR__.'/layouts/default.php');
            } ?>
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0
            </div>
            <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="/js/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/js/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
    $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- datepicker -->
    <script src="/js/bootstrap-datepicker.min.js"></script>
    <!-- timepicker -->
    <script src="/js/bootstrap-timepicker.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/js/adminlte.min.js"></script>
    <script type="text/javascript">
        $('.datepicker').datepicker({
            orientation: 'bottom',
            format: 'yyyy-mm-dd'
        });

        //Timepicker
        $('.timepicker').timepicker({
            showInputs: false
        })

        $(".date-selector").change(function(){
            var monthVal = $("#month-select").val();
            if (monthVal < 10) {
                monthVal = 0+monthVal;
            }
            var yearVal = $("#year-select").val();
            
            $.post('/change-date', { month: monthVal, year: yearVal, page: "<?php echo $function ?>" }, 
                function(returnedData){
                    console.log(returnedData);
                    $('#table-result').html(returnedData);
            });
        });

        $.ajaxSetup({
          cache: false
        });

        $(".accept-button").click(function () {
            var username_mhs = $(this).attr('username');
            var tgl = $(this).attr('tgl_mulai');
            var no_ruangan = $(this).attr('ruangan');

            $.post('/accept-ruang', { username: username_mhs, tgl_mulai: tgl, ruangan: no_ruangan }, 
                function(returnedData){
                    location.reload();
            });
        });

        $(".deny-button").click(function () {
            var username_mhs = $(this).attr('username');
            var tgl = $(this).attr('tgl_mulai');
            var no_ruangan = $(this).attr('ruangan');
            
            $.post('/deny-ruang', { username: username_mhs, tgl_mulai: tgl, ruangan: no_ruangan }, 
                function(returnedData){
                    location.reload();
            });
        });

        $(".print-item-button").click(function () {
            location.reload();
        });
    </script>
</body>

</html>