<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Siangbang - One Stop Borrowing Solution</title>
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>
    <!-- Custom styles for this template -->
    <link href="css/grayscale.min.css" rel="stylesheet">
</head>

<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <!-- <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a> -->
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <?php
                    if (isset($_SESSION['username'])) {
                      echo "<li class='nav-item'>
                        <a class='nav-link js-scroll-trigger' href='/dashboard'>Dashboard</a>
                      </li>";
                    }
                     
                    ?>
                    <li class="dropdown">
                        <?php if (!empty($_SESSION['username'])) : ?>
                          <a href='#'' class='nav-link js-scroll-trigger dropdown-toggle' data-toggle='dropdown'><?php echo $_SESSION['name'] ?> <span class='caret'></span></a>
                        <?php else: ?>
                          <a href='#'' class='nav-link js-scroll-trigger dropdown-toggle' data-toggle='dropdown'>Login <span class='caret'></span></a>
                        <?php endif; ?>

                        <ul id="login-dp" class="dropdown-menu">
                            <li>
                                <div class="row">
                                    <?php if (!empty($_SESSION['username'])) : ?>
                                        <a href=/logout class='col-md-12 bottom text-center'>
                                          <b>Logout</b>
                                        </a>
                                    <?php else: ?>
                                        <div class='col-md-12'>
                                        <form class='form' role='form' method='post' action='/login' accept-charset='UTF-8' id='login-nav'>
                                            <div class='form-group'>
                                                <label class='sr-only' for='exampleInputEmail2'>Username</label>
                                                <input name='username' type='text' class='form-control' id='exampleInputEmail2' placeholder='Username' required>
                                            </div>
                                            <div class='form-group'>
                                                <label class='sr-only' for='exampleInputPassword2'>Password</label>
                                                <input type='password' name='password' class='form-control' id='exampleInputPassword2' placeholder='Password' required>
                                            </div>
                                            <div class='form-group'>
                                                <button type='submit' name='sign-in' class='btn btn-primary btn-block'>Sign in</button>
                                            </div>
                                            <div class='checkbox'>
                                                <label>
                                                    <input type='checkbox'> keep me logged-in
                                                </label>
                                            </div>
                                        </form>
                                      </div>
                                    <?php endif; ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Intro Header -->
    <header class="masthead">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h1 class="brand-heading">SiangBang</h1>
                        <p class="intro-text">Your oone-stop solution for borrowing goods and rooms.
                            <br>Created by Basdat-F Group.</p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script> -->
    <!-- Custom scripts for this template -->
    <script src="js/grayscale.min.js"></script>
</body>

</html>